project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - research_statement.qmd
    - teaching_statement.qmd
    - cv.qmd
    - S&A.qmd
    - research.qmd
    

website:
  title: "Wesley T. Morris"
  navbar:
    left:
      - text: About Me
        menu:
          - href: S&A.qmd
            text: Service & Awards
          - href: research_statement.qmd
            text: Research Statement
          - href: teaching_statement.qmd
            text: Teaching Statement
      - text: CV
        href: cv.qmd
      - text: Research
        menu: 
          - href: research.qmd
            text: Publications
          - href: research_statement.qmd
            text: Research Statement
      
  google-analytics: "G-4S82ZPX7QZ"

format:
  html:
    theme: lux
    css: styles.css
    toc: false

