project:
  type: website
  output-dir: docs

website:
  title: "Wesley T. Morris"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - text: CV
        menu:
          - href: cv.qmd
            text: Curriculum Vitae
          - href: S&A.qmd
            text: Service & Awards
      - text: Research
        menu: 
          - href: research.qmd
            text: Publications
          - text: Research Statement
      
  google-analytics: "G-4S82ZPX7QZ"

format:
  html:
    theme: lux
    css: styles.css
    toc: false

