project:
  type: website
  output-dir: docs

website:
  title: "Wesley T. Morris"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
        menu:
          - href: about.qmd
            text: About Me
          - href: cv.qmd
            text: Curriculum Vitae
      - href: research.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



